/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CommerceApp;

import Adapters.FrameAdapter;
import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import util.FileProcess;
import util.Operation;

/**
 *
 * @author DELL
 */
public class RechercheOperationnel extends javax.swing.JDialog {
    private Operation operation;
    private FileProcess fileProcess;
    private ChoiceWindow choiceWindow;
    private String result;
    private JFrame parentFrame;
    /**
     * Creates new form rechercheOperationnel
     */
    public RechercheOperationnel(JFrame frm, Operation op, FileProcess fp) {
        super(frm, true);
        parentFrame = frm;
        operation = op;
        fileProcess = fp;
        choiceWindow = new ChoiceWindow(op);
        FrameAdapter.centerFrame(this);
        initComponents();
        rechercheLabel.setText(rechercheLabel.getText() + " "
                                + operation.getFrameTitle().toLowerCase());
        titleLabel.setText(titleLabel.getText() + " " 
                             +operation.getFrameTitle());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rechercheTextField = new javax.swing.JTextField();
        rechercheLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        rechercheTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheTextFieldActionPerformed(evt);
            }
        });
        rechercheTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rechercheTextFieldKeyTyped(evt);
            }
        });

        rechercheLabel.setText("rechercher");

        titleLabel.setBackground(new java.awt.Color(0, 0, 0));
        titleLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(204, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("RECHERCHE");
        titleLabel.setOpaque(true);

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        okButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                okButtonKeyPressed(evt);
            }
        });

        cancelButton.setText("Annuler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rechercheLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rechercheTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rechercheTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rechercheLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rechercheTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechercheTextFieldKeyTyped
        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar)) {
            evt.setKeyChar(Character.toUpperCase(keyChar));
        }
    }//GEN-LAST:event_rechercheTextFieldKeyTyped

    private void rechercheTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheTextFieldActionPerformed
        choiceWindow.show(rechercheTextField.getLocationOnScreen().x, 
                          rechercheTextField.getLocationOnScreen().y +
                                  rechercheTextField.getHeight(), 
                          rechercheTextField.getWidth(), 
                          rechercheTextField.getText());
    }//GEN-LAST:event_rechercheTextFieldActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        runOperationProcess();
    }//GEN-LAST:event_okButtonActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try{
            if (choiceWindow.getResult().size() != 0){
                result = (String)choiceWindow.getResult().get(0);
                rechercheTextField.setText(result);
                okButton.requestFocusInWindow();
            }
        }catch(NullPointerException ex){
            System.err.println(" y a pas moyen ...!");
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void okButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_okButtonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            runOperationProcess();
        }
    }//GEN-LAST:event_okButtonKeyPressed

    public String getResult(){
        return result;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RechercheOperationnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RechercheOperationnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RechercheOperationnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RechercheOperationnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RechercheOperationnel dialog = new RechercheOperationnel(
                                                    null,
                                                    Operation.CUSTOMER,
                                                    FileProcess.MODIFY);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel rechercheLabel;
    private javax.swing.JTextField rechercheTextField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    private void runOperationProcess() {
        switch(operation){
            case PRODUCT:
                OperateProductDialog f = new OperateProductDialog(
                                                    parentFrame,
                                                    fileProcess, 
                                                    result);
                f.setVisible(true);
            break;
            case CUSTOMER:
                //OperateOperatorDialog f = new OperateOperatorDialog(CUSTOMER, 
                //fileProcess, result);
            break;
            case PROVIDER:
                //OperateOperatorDialog f = new OperateOperatorDialog(PROVIDER, 
                //fileProcess, result);
            break;
        }
        dispose();
    }

    
}
