/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
import javax.swing.*;
public class Versement extends javax.swing.JFrame {
    private double versement = 0.0;
    private double newCredit = 0.0;
    private double total = 0.0;
    private double credit = 0.0;
    /**
     * Creates new form Versement
     */
    public Versement() {
        initComponents();
    }
    
    public Versement(double total, double credit){
        initComponents();
        this.total = total;
        this.credit = credit;
        totalTextField.setText(Double.toString(total));
        creditTextField.setText(Double.toString(credit));
        
    }
    /**
     * *
     */
    public double getVersement(){
        return versement;
    } 
    
    public double getNewCredit(){
        return newCredit;
    }
    
    public double getCredit(){
        return credit;
    }
    
    public double getTotal(){
        return total;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PaymentTypeCombo = new javax.swing.JComboBox<>();
        totalTextField = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        ancienSoldeLabel = new javax.swing.JLabel();
        creditTextField = new javax.swing.JTextField();
        paymentTextField = new javax.swing.JTextField();
        paymentLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        newCreditTextField = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("VERSEMENT");

        jLabel2.setText("Type de reglement");

        PaymentTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espece", "Versement", "Credit" }));
        PaymentTypeCombo.setFocusCycleRoot(true);
        PaymentTypeCombo.setNextFocusableComponent(ok);
        PaymentTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentTypeComboActionPerformed(evt);
            }
        });
        PaymentTypeCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PaymentTypeComboKeyPressed(evt);
            }
        });

        totalTextField.setText("00000.00");
        totalTextField.setFocusCycleRoot(true);

        totalLabel.setText("Total");

        ancienSoldeLabel.setText("ancien solde");

        creditTextField.setText("00000.00");

        paymentTextField.setText("00000.00");
        paymentTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentTextFieldFocusGained(evt);
            }
        });
        paymentTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paymentTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paymentTextFieldKeyTyped(evt);
            }
        });

        paymentLabel.setText("Versement");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Nouveau solde");

        newCreditTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        newCreditTextField.setForeground(new java.awt.Color(204, 0, 0));
        newCreditTextField.setText("00000.00");

        ok.setText("Ok");
        ok.setFocusCycleRoot(true);
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        ok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                okKeyPressed(evt);
            }
        });

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ok)
                    .addComponent(jLabel6)
                    .addComponent(ancienSoldeLabel)
                    .addComponent(jLabel2)
                    .addComponent(totalLabel)
                    .addComponent(paymentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaymentTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annuler))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {annuler, ok});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PaymentTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ancienSoldeLabel)
                    .addComponent(creditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentLabel))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(newCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(annuler))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // return a result containing the payment value
        // and the new credit calculated
        exitAfterOk();
    }//GEN-LAST:event_okActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_annulerActionPerformed

    private void paymentTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentTextFieldKeyTyped
        int keyChar = evt.getKeyChar();
        if (!Character.isDigit(keyChar)){
            evt.setKeyChar(new Character(java.awt.event.KeyEvent.CHAR_UNDEFINED));
	}
    }//GEN-LAST:event_paymentTextFieldKeyTyped

    private void paymentTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentTextFieldFocusGained
        paymentTextField.selectAll();
    }//GEN-LAST:event_paymentTextFieldFocusGained

    private void PaymentTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentTypeComboActionPerformed
        setPayment();
    }//GEN-LAST:event_PaymentTypeComboActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setPayment();
    }//GEN-LAST:event_formWindowOpened

    private void okKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_okKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            exitAfterOk();
        }
    }//GEN-LAST:event_okKeyPressed

    private void paymentTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentTextFieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            double d;
            try{
                double a = Double.parseDouble(totalTextField.getText());
                double b = Double.parseDouble(creditTextField.getText());
                double c = Double.parseDouble(paymentTextField.getText());
                d = a + b - c;
            }catch(java.lang.NumberFormatException e){
                double a = Double.parseDouble(totalTextField.getText());
                double b = Double.parseDouble(creditTextField.getText());
                d = a + b;
            }
            newCreditTextField.setText(Double.toString(d));
            ok.requestFocusInWindow();
        }
    }//GEN-LAST:event_paymentTextFieldKeyPressed

    private void PaymentTypeComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PaymentTypeComboKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            String type = (String)PaymentTypeCombo.getSelectedItem();
            switch(type){
                case "Espece":
                    paymentTextField.setText(totalTextField.getText());
                    newCreditTextField.setText(creditTextField.getText());
                    ok.requestFocusInWindow();
                    break;
                case "Versement":
                    paymentTextField.setText("");
                    paymentTextField.selectAll();
                    paymentTextField.requestFocusInWindow();
                    break;
                case "Credit":
                    ok.requestFocusInWindow();
                    break;
            }
        
            
        }
    }//GEN-LAST:event_PaymentTypeComboKeyPressed
    
    private void exitAfterOk() {
        try{
            versement = Double.parseDouble(paymentTextField.getText());
            newCredit = Double.parseDouble(newCreditTextField.getText());
        }catch(java.lang.NumberFormatException ex){
            versement = 0.0;
        }
        System.out.println(getVersement());
        System.out.println(getNewCredit());
        System.out.println(getCredit());
        System.out.println(getTotal());
        dispose();
    }
    private void setPayment(){
        String type = (String)PaymentTypeCombo.getSelectedItem();
        switch(type){
            case "Espece":
                paymentTextField.setVisible(false);
                paymentLabel.setVisible(false);
                newCreditTextField.setText(creditTextField.getText());
                break;
            case "Versement":
                paymentTextField.setVisible(true);
                paymentLabel.setVisible(true);
                break;
            case "Credit":
                paymentTextField.setVisible(false);
                paymentLabel.setVisible(false);
                double a = Double.parseDouble(creditTextField.getText());
                double b = Double.parseDouble(totalTextField.getText());
                double c = a + b;
                newCreditTextField.setText(Double.toString(c));
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> PaymentTypeCombo;
    private javax.swing.JLabel ancienSoldeLabel;
    private javax.swing.JButton annuler;
    private javax.swing.JTextField creditTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField newCreditTextField;
    private javax.swing.JButton ok;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.JTextField paymentTextField;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalTextField;
    // End of variables declaration//GEN-END:variables
}
